language: java
sudo: false
services:
  - mysql
jdk:
  - openjdk11
before_script:
  - mysql -e "set global sql_mode = ''"
  - mysql -uroot -e "create database crawler"
  - mysql -uroot crawler < src/config/schema.sql
after_success:
  - mvn clean test jacoco:report coveralls:report
