language: java
sudo: false
services:
  - mysql
jdk:
  - openjdk8
before_script:
  - mysql -uroot -e "create database crawler"
  - mysql -uroot crawler < src/config/schema.sql
after_success:
  - mvn clean test jacoco:report coveralls:report
